
services:
  db:  # The name of your service
    image: mysql/mysql-server:latest  # The image to use
    environment:  # Environment variables
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3309:3306"  # Port mapping
    expose:
      - "3306"
    container_name: antcat-db
    volumes:
      - ./sql-data:/docker-entrypoint-initdb.d  # Mount the initialization directory

  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: root
      DB_DATABASE: antcat_docker
      DB_PORT: 3306
      DB_HOST: db
      NO_DEV_MONKEY_PATCHES: "y"
    volumes:
      - .:/app
      - ./docker_dev/database.docker-dev.yml:/app/config/database.yml
      - ./config/server.yml.example:/app/config/server.yml
    ports:
      - "8080:8080"  # Map port 8080 of the container to port 8080 on the host
    container_name: antcat-app
    user: antcat
    stdin_open: true
    tty: true
