exclude:
  - 'vendor/**/*'

linters:
  AltText:
    enabled: true

  ClassesBeforeIds:
    enabled: false

  ConsecutiveComments:
    enabled: false

  ConsecutiveSilentScripts:
    enabled: false

  IdNames:
    enabled: false

  InlineStyles:
    enabled: false

  LineLength:
    enabled: false

  RepeatedId:
    enabled: false

  RuboCop:
    enabled: true
    ignored_cops:
      - Layout/ElseAlignment
      - Layout/EndAlignment
      - Layout/IndentationWidth
      - Layout/LineLength
      - Layout/SpaceInsideHashLiteralBraces
      - Layout/TrailingEmptyLines
      - Lint/Void
      - Metrics/BlockLength
      - Metrics/BlockNesting
      - Performance/CollectionLiteralInLoop
      - Rails/Presence
      - Style/ConditionalAssignment
      - Style/DoubleNegation
      - Style/FrozenStringLiteralComment
      - Style/IfInsideElse
      - Style/NegatedIf
      - Style/Next
      - Style/ParenthesesAroundCondition
      - Style/RedundantInterpolation
      - Style/SafeNavigation
      - Style/StringLiteralsInInterpolation
      - Style/UnlessElse

  SpaceBeforeScript:
    enabled: false

  SpaceInsideHashAttributes:
    enabled: false

  UnnecessaryStringOutput:
    enabled: false

  ViewLength:
    enabled: false
