require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'cookbooks/**/*'
    - 'data/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'solr/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

### Layout.

Layout/ArgumentAlignment:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/ClassStructure:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/HashAlignment:
  Enabled: false

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/LineLength:
  Max: 130
  Exclude:
    - 'app/controllers/quick_and_dirty_fixes_controller.rb'
    - 'app/database_scripts/database_scripts/**/*'

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Disabled due to false positives.
Layout/SpaceBeforeBrackets:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

### Lint.

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'features/step_definitions/**/*'
    - 'spec/**/*'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'lib/tasks/**/*.rake'

Lint/DuplicateBranch:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - 'spec/factories/**/*' # For transient attributes.

Lint/HeredocMethodCallPosition:
  Enabled: true

# Disabled because it does not handle `.rake` files.
Lint/RequireRelativeSelfPath:
  Enabled: false

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - delegate

Lint/UselessMethodDefinition:
  Enabled: false

# Metrics.

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/**/*'

Metrics/ClassLength:
  Enabled: false
  Max: 100
  CountAsOne:
    - array
    - hash
    - heredoc
  Exclude:
    - 'app/cleanup/**/*'
    - 'app/controllers/quick_and_dirty_fixes_controller.rb'
    - 'app/database_scripts/**/*'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
  Exclude:
    - 'app/database_scripts/database_scripts/**/*'

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 12
  Enabled: false

### Naming.

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

### Performance.

# Disabled because `filter_map` and `map.compact` are not identical.
Performance/MapCompact:
  Enabled: false

Performance/MethodObjectAsBlock:
  Enabled: false

Performance/Casecmp:
  Enabled: false

### Rails.

Rails/BulkChangeTable:
  Enabled: false

Rails/DefaultScope:
  Enabled: true

Rails/Delegate:
  Enabled: false

# Disabled because it flags dev ENV variables.
Rails/EnvironmentVariableAccess:
  Enabled: false

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

Rails/InverseOf:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/tasks/**/*'

Rails/OutputSafety:
  Enabled: false
  Exclude:
    - 'app/database_scripts/database_scripts/**/*'

# Disabled because it does not consider string constants to be strings.
Rails/ReflectionClassName:
  Enabled: false

Rails/RenderInline:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
  Exclude:
    - 'spec/**/*'

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Rails/WhereEquals:
  Enabled: false

Rails/WhereExists:
  Enabled: false

Rails/WhereNot:
  Enabled: false

# Indexes are not case sensitive in MySQL. Revisit if we ever migrate to Postgres.
Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/Validation:
  Enabled: false

### Rake.

Rake/Desc:
  Enabled: false

### RSpec.

RSpec/DescribedClass:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/FactoryBot/CreateList:
  EnforcedStyle: n_times

RSpec/ImplicitSubject:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/NotToNot:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

### Style.

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ArrayCoercion:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/ClassCheck:
  EnforcedStyle: is_a?

Style/ClassEqualityComparison:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - PERFORMANCE
    - HACK
    - REVIEW
    - NOTE
    - TMPCLEANUP

Style/DateTime:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'
    - 'config/environments/staging.rb'

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses_except_multiline

Style/MultilineBlockChain:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OptionHash:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

# Disabled to due to redundant begins blocks added on purpose for consistency.
Style/RedundantBegin:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/ReturnNil:
  Enabled: true

Style/Send:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInBlockArgs:
  Enabled: true

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/WordArray:
  Enabled: false
