#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'rvm', git: 'git://github.com/fnichol/chef-rvm.git', ref: 'v0.9.2'
cookbook 'mysql', '= 5.6.3'
cookbook 'nodejs', '~> 2.4.2'
cookbook 'jetty', '~> 0.1.5'
cookbook 'xvfb', '~> 2.0.0'
cookbook 'curl', '~> 2.0.1'
cookbook 'libqt4', '~> 0.1.0'
