#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "WARNING! Destructive command. Can only be run in the dev env."
  echo
  echo "Usage: RAILS_ENV=development ./$(basename "$0") data/db_dumps/antcat.2019-11-22T10-15-04.sql.gz"
  echo
  echo "Drops the db, imports the specified dump, and set the db environment to development."
  exit 0
fi

set -euo pipefail

[ "${RAILS_ENV:-}" != "development" ] && echo "RAILS_ENV must be 'development'" && exit 1

echo "*** Executing $0"

db_dump_path="${1:-}"
[ -z "${db_dump_path}" ] && echo "missing arg for db dump file" && exit 1

# ---

# To fix:
#   ERROR 3167 (HY000) at line 17: The 'INFORMATION_SCHEMA.SESSION_VARIABLES'
#   feature is disabled; see the documentation for 'show_compatibility_56'
# for mysql-client-5.7, but allow to fail for compatability with mysql-client-5.5.
set +e
echo 'SET GLOBAL show_compatibility_56 = ON;' | RAILS_ENV=development bundle exec rails db -p
set -e

# ---

cmd="zcat $db_dump_path"

if command -v pv &> /dev/null; then
  cmd+=" | pv -cN zcat"
fi

if [ "${SKIP_VERSIONS:-}" == "y" ]; then
  echo "Skipping PaperTrail versions"
  cmd+=" | sed '/INSERT INTO \`versions\`/d'"
else
  echo "Not skipping PaperTrail versions (use SKIP_VERSIONS=y to exclude them)"
fi

# Set environment because `SELECT * FROM ar_internal_metadata;` is set to "production"
# in exported db dumps. Same as: RAILS_ENV=development bundle exec rake db:environment:set
cmd+=$(cat <<'EOF'
 | sed 's/\(INSERT INTO `ar_internal_metadata` VALUES ('\''environment'"','"'\)production'"'"'/\1development'"'"'/g'
EOF
)

cmd+=' | RAILS_ENV=development bundle exec rails db -p'

echo "Executing: ${cmd}"

eval $cmd

# ---

echo "Import done."
