#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "WARNING! Destructive command. Can only be run in the dev env."
  echo
  echo "Usage: RAILS_ENV=development ./script/db_dump/$(basename $0)"
  echo
  echo "Requires the current user to have ssh access to EngineYard."
  exit 0
fi

set -euo pipefail

[ "${RAILS_ENV:-}" != "development" ] && echo "RAILS_ENV must be 'development'" && exit 1

echo "*** Executing $0"

full_path=$(realpath "$0")
dir_path=$(dirname "$full_path")

download_latest_results=$(bash "$dir_path/download_latest" | tee /dev/tty)
most_recent_local_path=$(echo "$download_latest_results" | grep 'Latest db dump -->' | awk -F"--> " '{print $2}')

if [ ! -f "$most_recent_local_path" ]; then
  echo "Could not find dump on local machine."
  exit 1
fi

"$dir_path/import" "$most_recent_local_path"
