#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "WARNING! Destructive command. Can only be run in the dev env."
  echo
  echo "Usage: RAILS_ENV=development ./script/db_dump/$(basename $0)"
  echo
  echo "Run command and pick file from list (from local db_dumps subdir)."
  exit 0
fi

set -euo pipefail

[ "${RAILS_ENV:-}" != "development" ] && echo "RAILS_ENV must be 'development'" && exit 1

echo "*** Executing $0"

full_path=$(realpath "$0")
dir_path=$(dirname "$full_path")

db_dumps_path="$dir_path/../../data/db_dumps"

# Via https://stackoverflow.com/questions/42427245/list-files-in-directory-as-menu-options-and-then-run-that-selected-script
prompt="Please select a file:"
options=( $(find $db_dumps_path -maxdepth 1 -type f -name "*sql.gz" -print0 | sort -z -r | xargs -0) )

PS3="$prompt "
select opt in "${options[@]}" "Quit" ; do
  if (( REPLY == 1 + ${#options[@]} )) ; then
    exit
  elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
    echo "You picked $opt which is file $REPLY"
    break
  else
    echo "Invalid option. Try another one."
  fi
done

bash "$dir_path/import" "$opt"
