#!/bin/bash

set -euo pipefail

[ "${RAILS_ENV:-}" != "development" ] && echo "RAILS_ENV must be 'development'" && exit 1

echo "*** Executing $0"

DISABLE_DATABASE_ENVIRONMENT_CHECK=1 RAILS_ENV=development bundle exec rails db:drop
RAILS_ENV=development bundle exec rails db:create
RAILS_ENV=development bundle exec rails db:schema:load
