version: "3.9"
services:
  db:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306" # Expose port for external access
    expose:
      - "3306" # Internal access within the Docker network
    container_name: antcat-db
    volumes:
      - ./sql-data:/docker-entrypoint-initdb.d
    networks:
      - antcat-network

  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: antcat
      DB_PORT: 3306
      DB_HOST: db # Use service name for DNS resolution
      NO_DEV_MONKEY_PATCHES: "y"
    volumes:
      - ..:/app
      - ./database.yml:/app/config/database.yml
      - ../config/server.yml.example:/app/config/server.yml
    ports:
      - "8080:8080"
    container_name: antcat-app
    user: antcat
    stdin_open: true
    tty: true
    command: ["/bin/bash", "-c", "dockerized_app/startup.sh"]
    networks:
      - antcat-network

networks:
  antcat-network:
    driver: bridge
