plain:    --format pretty -r features/support/env.rb -r features/support/plain.rb    -r features/step_definitions features/plain
enhanced: --format pretty -r features/support/env.rb -r features/support/enhanced.rb -r features/step_definitions features/enhanced
