#!/usr/bin/env ruby

require_relative 'site_notice_template'

site_notice_template = SiteNoticeTemplate.new

filename = site_notice_template.filename
message = site_notice_template.message

raise "File already exists: `#{filename}`" if File.exist?(filename)

File.open(filename, 'w') do |f|
  f.puts message
end

puts message
