class RemoveUnusedOriginAndAutoGeneratedColumns < ActiveRecord::Migration[5.1]
  def change
    remove_column :author_names, :verified, :boolean

    remove_column :author_names, :auto_generated, :boolean, default: false
    remove_column :citations, :auto_generated, :boolean, default: false
    remove_column :protonyms, :auto_generated, :boolean, default: false
    remove_column :reference_author_names, :auto_generated, :boolean, default: false
    remove_column :references, :auto_generated, :boolean, default: false
    remove_column :synonyms, :auto_generated, :boolean, default: false

    remove_column :author_names, :origin, :string
    remove_column :citations, :origin, :string
    remove_column :protonyms, :origin, :string
    remove_column :reference_author_names, :origin, :string
    remove_column :references, :origin, :string
    remove_column :synonyms, :origin, :string
    remove_column :journals, :origin, :string
  end
end


