#!/bin/bash

set -u

echo "*** Executing $0"

full_path=$(realpath "$0")
dir_path=$(dirname "$full_path")
remote_current_release_path='/data/antcat/current'

if [ "${RAILS_ENV:-}" = "production" ] || [ "${RAILS_ENV:-}" = "staging" ]; then
  pushd $remote_current_release_path || exit 1
fi

bash "$dir_path/kill"

bundle exec rake sunspot:solr:start
bundle exec rake sunspot:solr:reindex
