module DatabaseScripts
  class AutoGeneratedTaxa < DatabaseScript
    def results
      Taxon.where(auto_generated: true)
    end
  end
end

__END__

title: Auto-generated taxa
category: Catalog
tags: [new!]

description: >
