# frozen_string_literal: true

module DatabaseScripts
  class AutoGeneratedTaxa < DatabaseScript
    def results
      Taxon.where(auto_generated: true)
    end
  end
end

__END__

title: Auto-generated taxa

section: list
category: Catalog
tags: []

description: >

related_scripts:
  - AutoGeneratedTaxa
  - HolOriginTaxa
  - MigrationOriginTaxa
  - UnavailableMisspellings
  - UnavailableUncategorizedTaxa
