module DatabaseScripts
  class AutoGeneratedTaxa < DatabaseScript
    def results
      Taxon.where(auto_generated: true)
    end
  end
end

__END__

description: >

tags: [new!]
topic_areas: [catalog]
