module DatabaseScripts
  class MigrationOriginTaxa < DatabaseScript
    def results
      Taxon.where(origin: 'migration')
    end

    def render
      as_table do |t|
        t.header :taxon, :status, :protonym
        t.rows do |taxon|
          [
            markdown_taxon_link(taxon),
            taxon.status,
            taxon.protonym.decorate.link_to_protonym
          ]
        end
      end
    end
  end
end

__END__

title: Migration-origin taxa
category: Catalog
tags: [new!]

issue_description:

description: >

related_scripts:
  - AutoGeneratedTaxa
  - HolOriginTaxa
  - MigrationOriginTaxa
  - UnavailableMisspellings
  - UnavailableUncategorizedTaxa
  - UnavailableUncategorizedTaxaTouchedByEditors
