module DatabaseScripts
  class UnavailableUncategorizedTaxa < DatabaseScript
    SHOW_WHAT_LINKS_HERE = false

    def results
      Taxon.where(status: Status::UNAVAILABLE_UNCATEGORIZED).includes(:current_valid_taxon)
    end

    def render
      as_table do |t|
        if SHOW_WHAT_LINKS_HERE
          t.header :taxon, :status, :current_valid_taxon, :current_valid_taxon_status,
            :any_what_links_here_columns?, :any_what_links_here_taxts?, :any?, :what_links_here
        else
          t.header :taxon, :status, :current_valid_taxon, :current_valid_taxon_status
        end

        t.rows do |taxon|
          current_valid_taxon = taxon.current_valid_taxon

          [
            markdown_taxon_link(taxon),
            taxon.status,
            markdown_taxon_link(current_valid_taxon),
            current_valid_taxon.status,

            *what_links_here_coumns(taxon)
          ]
        end
      end
    end

    private

      def what_links_here_coumns taxon
        return [] unless SHOW_WHAT_LINKS_HERE

        wlh_columns = Taxa::WhatLinksHereColumns[taxon, predicate: true]
        wlh_taxts = Taxa::WhatLinksHereTaxts[taxon, predicate: true]

        [
          ('Yes' if wlh_columns),
          ('Yes' if wlh_taxts),
          ('Yes' if wlh_columns || wlh_taxts),
          link_to('What Links Here', taxon_what_links_here_path(taxon), class: 'btn-normal btn-tiny')
        ]
      end
  end
end

__END__

category: Catalog

issue_description: This taxon has the status "unavailable uncategorized".

description: >
  Taxa with the status `unavailable uncategorized`. We want to convert these to other statuses.

related_scripts:
  - AutoGeneratedTaxa
  - UnavailableMisspellings
  - UnavailableUncategorizedTaxaTouchedByEditors
  - UnavailableUncategorizedTaxa
